import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.scss'

export default function Home(): JSX.Element {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hello</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello world!</h1>
    </div>
  )
}
